//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DynamicsNAV365_StaffPortal.LoanManagementWebServiceReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoanManagementWebService_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService")]
    public partial class LoanManagementWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLoanProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoanApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoanApplicationStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback OpenLoanApplicationNoExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckLoanApplicationExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateLoanApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyLoanApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckLoanApplicationApprovalWorkflowEnabledOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendLoanApplicationApprovalRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelLoanApplicationApprovalRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LoanManagementWebService() {
            this.Url = "http://cihebsvr.cihebk.local:7047/CIHEBK/WS/CIHEBKENYA/Codeunit/LoanManagementWeb" +
                "Service";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLoanProductsCompletedEventHandler GetLoanProductsCompleted;
        
        /// <remarks/>
        public event GetLoanApplicationsCompletedEventHandler GetLoanApplicationsCompleted;
        
        /// <remarks/>
        public event GetLoanApplicationStatusCompletedEventHandler GetLoanApplicationStatusCompleted;
        
        /// <remarks/>
        public event OpenLoanApplicationNoExistsCompletedEventHandler OpenLoanApplicationNoExistsCompleted;
        
        /// <remarks/>
        public event CheckLoanApplicationExistsCompletedEventHandler CheckLoanApplicationExistsCompleted;
        
        /// <remarks/>
        public event CreateLoanApplicationCompletedEventHandler CreateLoanApplicationCompleted;
        
        /// <remarks/>
        public event ModifyLoanApplicationCompletedEventHandler ModifyLoanApplicationCompleted;
        
        /// <remarks/>
        public event CheckLoanApplicationApprovalWorkflowEnabledCompletedEventHandler CheckLoanApplicationApprovalWorkflowEnabledCompleted;
        
        /// <remarks/>
        public event SendLoanApplicationApprovalRequestCompletedEventHandler SendLoanApplicationApprovalRequestCompleted;
        
        /// <remarks/>
        public event CancelLoanApplicationApprovalRequestCompletedEventHandler CancelLoanApplicationApprovalRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:GetLoanProducts", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="GetLoanProducts_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetLoanProducts() {
            object[] results = this.Invoke("GetLoanProducts", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanProductsAsync() {
            this.GetLoanProductsAsync(null);
        }
        
        /// <remarks/>
        public void GetLoanProductsAsync(object userState) {
            if ((this.GetLoanProductsOperationCompleted == null)) {
                this.GetLoanProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanProductsOperationCompleted);
            }
            this.InvokeAsync("GetLoanProducts", new object[0], this.GetLoanProductsOperationCompleted, userState);
        }
        
        private void OnGetLoanProductsOperationCompleted(object arg) {
            if ((this.GetLoanProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanProductsCompleted(this, new GetLoanProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:GetLoanApplicati" +
            "ons", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="GetLoanApplications_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetLoanApplications(string applicationNo, string employeeNo) {
            object[] results = this.Invoke("GetLoanApplications", new object[] {
                        applicationNo,
                        employeeNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanApplicationsAsync(string applicationNo, string employeeNo) {
            this.GetLoanApplicationsAsync(applicationNo, employeeNo, null);
        }
        
        /// <remarks/>
        public void GetLoanApplicationsAsync(string applicationNo, string employeeNo, object userState) {
            if ((this.GetLoanApplicationsOperationCompleted == null)) {
                this.GetLoanApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanApplicationsOperationCompleted);
            }
            this.InvokeAsync("GetLoanApplications", new object[] {
                        applicationNo,
                        employeeNo}, this.GetLoanApplicationsOperationCompleted, userState);
        }
        
        private void OnGetLoanApplicationsOperationCompleted(object arg) {
            if ((this.GetLoanApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanApplicationsCompleted(this, new GetLoanApplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:GetLoanApplicati" +
            "onStatus", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="GetLoanApplicationStatus_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetLoanApplicationStatus(string applicationNo) {
            object[] results = this.Invoke("GetLoanApplicationStatus", new object[] {
                        applicationNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanApplicationStatusAsync(string applicationNo) {
            this.GetLoanApplicationStatusAsync(applicationNo, null);
        }
        
        /// <remarks/>
        public void GetLoanApplicationStatusAsync(string applicationNo, object userState) {
            if ((this.GetLoanApplicationStatusOperationCompleted == null)) {
                this.GetLoanApplicationStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanApplicationStatusOperationCompleted);
            }
            this.InvokeAsync("GetLoanApplicationStatus", new object[] {
                        applicationNo}, this.GetLoanApplicationStatusOperationCompleted, userState);
        }
        
        private void OnGetLoanApplicationStatusOperationCompleted(object arg) {
            if ((this.GetLoanApplicationStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanApplicationStatusCompleted(this, new GetLoanApplicationStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:OpenLoanApplicat" +
            "ionNoExists", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="OpenLoanApplicationNoExists_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string OpenLoanApplicationNoExists(string employeeNo) {
            object[] results = this.Invoke("OpenLoanApplicationNoExists", new object[] {
                        employeeNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OpenLoanApplicationNoExistsAsync(string employeeNo) {
            this.OpenLoanApplicationNoExistsAsync(employeeNo, null);
        }
        
        /// <remarks/>
        public void OpenLoanApplicationNoExistsAsync(string employeeNo, object userState) {
            if ((this.OpenLoanApplicationNoExistsOperationCompleted == null)) {
                this.OpenLoanApplicationNoExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpenLoanApplicationNoExistsOperationCompleted);
            }
            this.InvokeAsync("OpenLoanApplicationNoExists", new object[] {
                        employeeNo}, this.OpenLoanApplicationNoExistsOperationCompleted, userState);
        }
        
        private void OnOpenLoanApplicationNoExistsOperationCompleted(object arg) {
            if ((this.OpenLoanApplicationNoExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpenLoanApplicationNoExistsCompleted(this, new OpenLoanApplicationNoExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:CheckLoanApplica" +
            "tionExists", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="CheckLoanApplicationExists_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckLoanApplicationExists(string applicationNo, string employeeNo) {
            object[] results = this.Invoke("CheckLoanApplicationExists", new object[] {
                        applicationNo,
                        employeeNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckLoanApplicationExistsAsync(string applicationNo, string employeeNo) {
            this.CheckLoanApplicationExistsAsync(applicationNo, employeeNo, null);
        }
        
        /// <remarks/>
        public void CheckLoanApplicationExistsAsync(string applicationNo, string employeeNo, object userState) {
            if ((this.CheckLoanApplicationExistsOperationCompleted == null)) {
                this.CheckLoanApplicationExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLoanApplicationExistsOperationCompleted);
            }
            this.InvokeAsync("CheckLoanApplicationExists", new object[] {
                        applicationNo,
                        employeeNo}, this.CheckLoanApplicationExistsOperationCompleted, userState);
        }
        
        private void OnCheckLoanApplicationExistsOperationCompleted(object arg) {
            if ((this.CheckLoanApplicationExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckLoanApplicationExistsCompleted(this, new CheckLoanApplicationExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:CreateLoanApplic" +
            "ation", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="CreateLoanApplication_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CreateLoanApplication(string employeeNo) {
            object[] results = this.Invoke("CreateLoanApplication", new object[] {
                        employeeNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateLoanApplicationAsync(string employeeNo) {
            this.CreateLoanApplicationAsync(employeeNo, null);
        }
        
        /// <remarks/>
        public void CreateLoanApplicationAsync(string employeeNo, object userState) {
            if ((this.CreateLoanApplicationOperationCompleted == null)) {
                this.CreateLoanApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateLoanApplicationOperationCompleted);
            }
            this.InvokeAsync("CreateLoanApplication", new object[] {
                        employeeNo}, this.CreateLoanApplicationOperationCompleted, userState);
        }
        
        private void OnCreateLoanApplicationOperationCompleted(object arg) {
            if ((this.CreateLoanApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateLoanApplicationCompleted(this, new CreateLoanApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:ModifyLoanApplic" +
            "ation", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="ModifyLoanApplication_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ModifyLoanApplication(string applicationNo, string productType, decimal amountRequested, string purpose) {
            object[] results = this.Invoke("ModifyLoanApplication", new object[] {
                        applicationNo,
                        productType,
                        amountRequested,
                        purpose});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyLoanApplicationAsync(string applicationNo, string productType, decimal amountRequested, string purpose) {
            this.ModifyLoanApplicationAsync(applicationNo, productType, amountRequested, purpose, null);
        }
        
        /// <remarks/>
        public void ModifyLoanApplicationAsync(string applicationNo, string productType, decimal amountRequested, string purpose, object userState) {
            if ((this.ModifyLoanApplicationOperationCompleted == null)) {
                this.ModifyLoanApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyLoanApplicationOperationCompleted);
            }
            this.InvokeAsync("ModifyLoanApplication", new object[] {
                        applicationNo,
                        productType,
                        amountRequested,
                        purpose}, this.ModifyLoanApplicationOperationCompleted, userState);
        }
        
        private void OnModifyLoanApplicationOperationCompleted(object arg) {
            if ((this.ModifyLoanApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyLoanApplicationCompleted(this, new ModifyLoanApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:CheckLoanApplica" +
            "tionApprovalWorkflowEnabled", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="CheckLoanApplicationApprovalWorkflowEnabled_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckLoanApplicationApprovalWorkflowEnabled(string applicationNo) {
            object[] results = this.Invoke("CheckLoanApplicationApprovalWorkflowEnabled", new object[] {
                        applicationNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckLoanApplicationApprovalWorkflowEnabledAsync(string applicationNo) {
            this.CheckLoanApplicationApprovalWorkflowEnabledAsync(applicationNo, null);
        }
        
        /// <remarks/>
        public void CheckLoanApplicationApprovalWorkflowEnabledAsync(string applicationNo, object userState) {
            if ((this.CheckLoanApplicationApprovalWorkflowEnabledOperationCompleted == null)) {
                this.CheckLoanApplicationApprovalWorkflowEnabledOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLoanApplicationApprovalWorkflowEnabledOperationCompleted);
            }
            this.InvokeAsync("CheckLoanApplicationApprovalWorkflowEnabled", new object[] {
                        applicationNo}, this.CheckLoanApplicationApprovalWorkflowEnabledOperationCompleted, userState);
        }
        
        private void OnCheckLoanApplicationApprovalWorkflowEnabledOperationCompleted(object arg) {
            if ((this.CheckLoanApplicationApprovalWorkflowEnabledCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckLoanApplicationApprovalWorkflowEnabledCompleted(this, new CheckLoanApplicationApprovalWorkflowEnabledCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:SendLoanApplicat" +
            "ionApprovalRequest", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="SendLoanApplicationApprovalRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool SendLoanApplicationApprovalRequest(string applicationNo) {
            object[] results = this.Invoke("SendLoanApplicationApprovalRequest", new object[] {
                        applicationNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendLoanApplicationApprovalRequestAsync(string applicationNo) {
            this.SendLoanApplicationApprovalRequestAsync(applicationNo, null);
        }
        
        /// <remarks/>
        public void SendLoanApplicationApprovalRequestAsync(string applicationNo, object userState) {
            if ((this.SendLoanApplicationApprovalRequestOperationCompleted == null)) {
                this.SendLoanApplicationApprovalRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendLoanApplicationApprovalRequestOperationCompleted);
            }
            this.InvokeAsync("SendLoanApplicationApprovalRequest", new object[] {
                        applicationNo}, this.SendLoanApplicationApprovalRequestOperationCompleted, userState);
        }
        
        private void OnSendLoanApplicationApprovalRequestOperationCompleted(object arg) {
            if ((this.SendLoanApplicationApprovalRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendLoanApplicationApprovalRequestCompleted(this, new SendLoanApplicationApprovalRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService:CancelLoanApplic" +
            "ationApprovalRequest", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", ResponseElementName="CancelLoanApplicationApprovalRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/LoanManagementWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CancelLoanApplicationApprovalRequest(string applicationNo) {
            object[] results = this.Invoke("CancelLoanApplicationApprovalRequest", new object[] {
                        applicationNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelLoanApplicationApprovalRequestAsync(string applicationNo) {
            this.CancelLoanApplicationApprovalRequestAsync(applicationNo, null);
        }
        
        /// <remarks/>
        public void CancelLoanApplicationApprovalRequestAsync(string applicationNo, object userState) {
            if ((this.CancelLoanApplicationApprovalRequestOperationCompleted == null)) {
                this.CancelLoanApplicationApprovalRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelLoanApplicationApprovalRequestOperationCompleted);
            }
            this.InvokeAsync("CancelLoanApplicationApprovalRequest", new object[] {
                        applicationNo}, this.CancelLoanApplicationApprovalRequestOperationCompleted, userState);
        }
        
        private void OnCancelLoanApplicationApprovalRequestOperationCompleted(object arg) {
            if ((this.CancelLoanApplicationApprovalRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelLoanApplicationApprovalRequestCompleted(this, new CancelLoanApplicationApprovalRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetLoanProductsCompletedEventHandler(object sender, GetLoanProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetLoanApplicationsCompletedEventHandler(object sender, GetLoanApplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanApplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanApplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetLoanApplicationStatusCompletedEventHandler(object sender, GetLoanApplicationStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanApplicationStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanApplicationStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OpenLoanApplicationNoExistsCompletedEventHandler(object sender, OpenLoanApplicationNoExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpenLoanApplicationNoExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpenLoanApplicationNoExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckLoanApplicationExistsCompletedEventHandler(object sender, CheckLoanApplicationExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckLoanApplicationExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckLoanApplicationExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateLoanApplicationCompletedEventHandler(object sender, CreateLoanApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateLoanApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateLoanApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ModifyLoanApplicationCompletedEventHandler(object sender, ModifyLoanApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyLoanApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyLoanApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckLoanApplicationApprovalWorkflowEnabledCompletedEventHandler(object sender, CheckLoanApplicationApprovalWorkflowEnabledCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckLoanApplicationApprovalWorkflowEnabledCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckLoanApplicationApprovalWorkflowEnabledCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendLoanApplicationApprovalRequestCompletedEventHandler(object sender, SendLoanApplicationApprovalRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendLoanApplicationApprovalRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendLoanApplicationApprovalRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CancelLoanApplicationApprovalRequestCompletedEventHandler(object sender, CancelLoanApplicationApprovalRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelLoanApplicationApprovalRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelLoanApplicationApprovalRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591