//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicsNAV365_StaffPortal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://102.133.239.194:3032/Regent/WS/Regent%20Ltd/Codeunit/EmployeeAppraisalMana" +
            "gementWS")]
        public string DynamicsNAV365_StaffPortal_EmployeeAppraisalManagementWebServiceRef_EmployeeAppraisalManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_EmployeeAppraisalManagementWebServiceRef_EmployeeAppra" +
                    "isalManagementWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://102.133.239.194:3032/Regent/WS/Regent%20Ltd/Codeunit/EmployeeTrainingManag" +
            "ementWS")]
        public string DynamicsNAV365_StaffPortal_EmployeeTrainingManagementWebServiceRef_EmployeeTrainingManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_EmployeeTrainingManagementWebServiceRef_EmployeeTraini" +
                    "ngManagementWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://")]
        public string protocol {
            get {
                return ((string)(this["protocol"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://")]
        public string secureprotocol {
            get {
                return ((string)(this["secureprotocol"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Panache Technohub Limited.")]
        public string PoweredBy {
            get {
                return ((string)(this["PoweredBy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Employee Self-Service Portal")]
        public string AppName {
            get {
                return ((string)(this["AppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://panachetechnohub.co.ke/")]
        public string CompanyWebsite {
            get {
                return ((string)(this["CompanyWebsite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http")]
        public string passwordResetProtocol {
            get {
                return ((string)(this["passwordResetProtocol"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nav365@")]
        public string ConnPassword {
            get {
                return ((string)(this["ConnPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8047")]
        public string SOAPPortNumber {
            get {
                return ((string)(this["SOAPPortNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8048")]
        public string ODATAPortNumber {
            get {
                return ((string)(this["ODATAPortNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPTIVEN")]
        public string DynamicsNAVServiceName {
            get {
                return ((string)(this["DynamicsNAVServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Optiven R.E")]
        public string DefaultCompanyURLName {
            get {
                return ((string)(this["DefaultCompanyURLName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DynamicsNAVServer2 {
            get {
                return ((string)(this["DynamicsNAVServer2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("erp2")]
        public string ConnUsername {
            get {
                return ((string)(this["ConnUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/LoanManagementWebService")]
        public string DynamicsNAV365_StaffPortal_LoanManagementWebServiceReference_LoanManagementWebService {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_LoanManagementWebServiceReference_LoanManagementWebSer" +
                    "vice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/MemoSalaryAdvanceWebServi" +
            "ce")]
        public string DynamicsNAV365_StaffPortal_MemoSalaryAdvanceWebServiceReference_MemoSalaryAdvanceWebService {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_MemoSalaryAdvanceWebServiceReference_MemoSalaryAdvance" +
                    "WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/PerformanceManagement")]
        public string DynamicsNAV365_StaffPortal_PerformanceManagementWebServiceReference_PerformanceManagement {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_PerformanceManagementWebServiceReference_PerformanceMa" +
                    "nagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/ProjectManagementWS")]
        public string DynamicsNAV365_StaffPortal_ProjectManagementWebServiceReference_ProjectManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_ProjectManagementWebServiceReference_ProjectManagement" +
                    "WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven%20R.E/Codeunit/PortalApprovalManager")]
        public string DynamicsNAV365_StaffPortal_ApprovalManagementWebServiceReference_PortalApprovalManager {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_ApprovalManagementWebServiceReference_PortalApprovalMa" +
                    "nager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/DocumentMgmt")]
        public string DynamicsNAV365_StaffPortal_DocumentManagementWebServiceRef_DocumentMgmt {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_DocumentManagementWebServiceRef_DocumentMgmt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven%20R.E/Codeunit/EmployeeAccountWebServi" +
            "ce")]
        public string DynamicsNAV365_StaffPortal_EmployeeAccountWebServiceReference_EmployeeAccountWebService {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_EmployeeAccountWebServiceReference_EmployeeAccountWebS" +
                    "ervice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven%20R.E/Codeunit/HumanResourceManagement" +
            "WS")]
        public string DynamicsNAV365_StaffPortal_HumanResourceManagmentWebServiceReference_HumanResourceManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_HumanResourceManagmentWebServiceReference_HumanResourc" +
                    "eManagementWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/PayrollManagementWS")]
        public string DynamicsNAV365_StaffPortal_PayrollManagementWebServiceReference_PayrollManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_PayrollManagementWebServiceReference_PayrollManagement" +
                    "WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/FundsClaimManagementWebSe" +
            "rvice")]
        public string DynamicsNAV365_StaffPortal_FundsClaimManagementWebServiceReference_FundsClaimManagementWebService {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_FundsClaimManagementWebServiceReference_FundsClaimMana" +
                    "gementWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/InventoryManagementWS")]
        public string DynamicsNAV365_StaffPortal_InventoryManagementWebServiceReference_InventoryManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_InventoryManagementWebServiceReference_InventoryManage" +
                    "mentWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/ProcurementManagementWS")]
        public string DynamicsNAV365_StaffPortal_ProcurementManagementWebServiceReference_ProcurementManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_ProcurementManagementWebServiceReference_ProcurementMa" +
                    "nagementWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/ActivityRequest")]
        public string DynamicsNAV365_StaffPortal_ActivityRequestWs_ActivityRequest {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_ActivityRequestWs_ActivityRequest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Codeunit/TimeSheetWS")]
        public string DynamicsNAV365_StaffPortal_TimeSheet_TimeSheetWS {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_TimeSheet_TimeSheetWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven%20R.E/Codeunit/FundsManagementWebServi" +
            "ce")]
        public string DynamicsNAV365_StaffPortal_FundsManagementWebServiceReference_FundsManagementWebService {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_FundsManagementWebServiceReference_FundsManagementWebS" +
                    "ervice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Page/ImprestStaffAdvance")]
        public string DynamicsNAV365_StaffPortal_Page_ImprestStaffAdvance {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_Page_ImprestStaffAdvance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven R.E/Page/ImprestStaffAdvance")]
        public string DynamicsNAV365_StaffPortal_local_cihebk_cihebsvr_ImprestStaffAdvance_Service {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_local_cihebk_cihebsvr_ImprestStaffAdvance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven%20R.E/Codeunit/StaffAdvance")]
        public string DynamicsNAV365_StaffPortal_StaffAdvanceWebServiceReference2_StaffAdvance {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_StaffAdvanceWebServiceReference2_StaffAdvance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.5")]
        public string DynamicsNAVServer {
            get {
                return ((string)(this["DynamicsNAVServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Optiven Group")]
        public string CompanyName {
            get {
                return ((string)(this["CompanyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5/:8047/Optiven/WS/Optiven R.E/Codeunit/PerformanceManagement")]
        public string DynamicsNAV365_StaffPortal_PerformanceManagement_PerformanceManagement {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_PerformanceManagement_PerformanceManagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/ReplaceWithAPercentEncodedCompanyName/Codeunit" +
            "/Approvals_Mgmt")]
        public string DynamicsNAV365_StaffPortal_NativeApprovalsMgmtWebReference_Approvals_Mgmt {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_NativeApprovalsMgmtWebReference_Approvals_Mgmt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/Optiven%20R.E/Page/Property_Card")]
        public string DynamicsNAV365_StaffPortal_Property_Card_Property_Card_Service {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_Property_Card_Property_Card_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.5:8047/Optiven/WS/ReplaceWithAPercentEncodedCompanyName/Codeunit" +
            "/ProjectPortalUpdate")]
        public string DynamicsNAV365_StaffPortal_ProjectPortalUpdate_ProjectPortalUpdate {
            get {
                return ((string)(this["DynamicsNAV365_StaffPortal_ProjectPortalUpdate_ProjectPortalUpdate"]));
            }
        }
    }
}
