//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DynamicsNAV365_StaffPortal.ApprovalManagementWebServiceReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PortalApprovalManager_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager")]
    public partial class PortalApprovalManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOpenApprovalEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApprovedApprovalEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRejectedApprovalEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApproversOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectionCommentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveImprestRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectImprestRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveLeaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectLeaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveStaffRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectStaffRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveRequisitionCopyOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApprovePurchaseOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectPurchaseOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveRFXOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectRFXOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveBidAnalysisOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectBidAnalysisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApprovePaymentVoucherOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectPaymentVoucherOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendApprovalRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PortalApprovalManager() {
            this.Url = global::DynamicsNAV365_StaffPortal.Properties.Settings.Default.DynamicsNAV365_StaffPortal_ApprovalManagementWebServiceReference_PortalApprovalManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOpenApprovalEntriesCompletedEventHandler GetOpenApprovalEntriesCompleted;
        
        /// <remarks/>
        public event GetApprovedApprovalEntriesCompletedEventHandler GetApprovedApprovalEntriesCompleted;
        
        /// <remarks/>
        public event GetRejectedApprovalEntriesCompletedEventHandler GetRejectedApprovalEntriesCompleted;
        
        /// <remarks/>
        public event GetApproversCompletedEventHandler GetApproversCompleted;
        
        /// <remarks/>
        public event RejectionCommentsCompletedEventHandler RejectionCommentsCompleted;
        
        /// <remarks/>
        public event ApproveImprestRequestCompletedEventHandler ApproveImprestRequestCompleted;
        
        /// <remarks/>
        public event RejectImprestRequestCompletedEventHandler RejectImprestRequestCompleted;
        
        /// <remarks/>
        public event ApproveLeaveCompletedEventHandler ApproveLeaveCompleted;
        
        /// <remarks/>
        public event RejectLeaveCompletedEventHandler RejectLeaveCompleted;
        
        /// <remarks/>
        public event ApproveStaffRequisitionCompletedEventHandler ApproveStaffRequisitionCompleted;
        
        /// <remarks/>
        public event RejectStaffRequisitionCompletedEventHandler RejectStaffRequisitionCompleted;
        
        /// <remarks/>
        public event ApproveRequisitionCompletedEventHandler ApproveRequisitionCompleted;
        
        /// <remarks/>
        public event ApproveRequisitionCopyCompletedEventHandler ApproveRequisitionCopyCompleted;
        
        /// <remarks/>
        public event RejectRequisitionCompletedEventHandler RejectRequisitionCompleted;
        
        /// <remarks/>
        public event ApprovePurchaseOrderCompletedEventHandler ApprovePurchaseOrderCompleted;
        
        /// <remarks/>
        public event RejectPurchaseOrderCompletedEventHandler RejectPurchaseOrderCompleted;
        
        /// <remarks/>
        public event ApproveRFXCompletedEventHandler ApproveRFXCompleted;
        
        /// <remarks/>
        public event RejectRFXCompletedEventHandler RejectRFXCompleted;
        
        /// <remarks/>
        public event ApproveBidAnalysisCompletedEventHandler ApproveBidAnalysisCompleted;
        
        /// <remarks/>
        public event RejectBidAnalysisCompletedEventHandler RejectBidAnalysisCompleted;
        
        /// <remarks/>
        public event ApprovePaymentVoucherCompletedEventHandler ApprovePaymentVoucherCompleted;
        
        /// <remarks/>
        public event RejectPaymentVoucherCompletedEventHandler RejectPaymentVoucherCompleted;
        
        /// <remarks/>
        public event SendApprovalRequestCompletedEventHandler SendApprovalRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:GetOpenApprovalEntr" +
            "ies", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="GetOpenApprovalEntries_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetOpenApprovalEntries(string employeeNo, string documentNo) {
            object[] results = this.Invoke("GetOpenApprovalEntries", new object[] {
                        employeeNo,
                        documentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOpenApprovalEntriesAsync(string employeeNo, string documentNo) {
            this.GetOpenApprovalEntriesAsync(employeeNo, documentNo, null);
        }
        
        /// <remarks/>
        public void GetOpenApprovalEntriesAsync(string employeeNo, string documentNo, object userState) {
            if ((this.GetOpenApprovalEntriesOperationCompleted == null)) {
                this.GetOpenApprovalEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOpenApprovalEntriesOperationCompleted);
            }
            this.InvokeAsync("GetOpenApprovalEntries", new object[] {
                        employeeNo,
                        documentNo}, this.GetOpenApprovalEntriesOperationCompleted, userState);
        }
        
        private void OnGetOpenApprovalEntriesOperationCompleted(object arg) {
            if ((this.GetOpenApprovalEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOpenApprovalEntriesCompleted(this, new GetOpenApprovalEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:GetApprovedApproval" +
            "Entries", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="GetApprovedApprovalEntries_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetApprovedApprovalEntries(string employeeNo, string documentNo) {
            object[] results = this.Invoke("GetApprovedApprovalEntries", new object[] {
                        employeeNo,
                        documentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetApprovedApprovalEntriesAsync(string employeeNo, string documentNo) {
            this.GetApprovedApprovalEntriesAsync(employeeNo, documentNo, null);
        }
        
        /// <remarks/>
        public void GetApprovedApprovalEntriesAsync(string employeeNo, string documentNo, object userState) {
            if ((this.GetApprovedApprovalEntriesOperationCompleted == null)) {
                this.GetApprovedApprovalEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprovedApprovalEntriesOperationCompleted);
            }
            this.InvokeAsync("GetApprovedApprovalEntries", new object[] {
                        employeeNo,
                        documentNo}, this.GetApprovedApprovalEntriesOperationCompleted, userState);
        }
        
        private void OnGetApprovedApprovalEntriesOperationCompleted(object arg) {
            if ((this.GetApprovedApprovalEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApprovedApprovalEntriesCompleted(this, new GetApprovedApprovalEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:GetRejectedApproval" +
            "Entries", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="GetRejectedApprovalEntries_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetRejectedApprovalEntries(string employeeNo, string documentNo) {
            object[] results = this.Invoke("GetRejectedApprovalEntries", new object[] {
                        employeeNo,
                        documentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRejectedApprovalEntriesAsync(string employeeNo, string documentNo) {
            this.GetRejectedApprovalEntriesAsync(employeeNo, documentNo, null);
        }
        
        /// <remarks/>
        public void GetRejectedApprovalEntriesAsync(string employeeNo, string documentNo, object userState) {
            if ((this.GetRejectedApprovalEntriesOperationCompleted == null)) {
                this.GetRejectedApprovalEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRejectedApprovalEntriesOperationCompleted);
            }
            this.InvokeAsync("GetRejectedApprovalEntries", new object[] {
                        employeeNo,
                        documentNo}, this.GetRejectedApprovalEntriesOperationCompleted, userState);
        }
        
        private void OnGetRejectedApprovalEntriesOperationCompleted(object arg) {
            if ((this.GetRejectedApprovalEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRejectedApprovalEntriesCompleted(this, new GetRejectedApprovalEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:GetApprovers", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="GetApprovers_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetApprovers(string employeeNo, string documentNo) {
            object[] results = this.Invoke("GetApprovers", new object[] {
                        employeeNo,
                        documentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetApproversAsync(string employeeNo, string documentNo) {
            this.GetApproversAsync(employeeNo, documentNo, null);
        }
        
        /// <remarks/>
        public void GetApproversAsync(string employeeNo, string documentNo, object userState) {
            if ((this.GetApproversOperationCompleted == null)) {
                this.GetApproversOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApproversOperationCompleted);
            }
            this.InvokeAsync("GetApprovers", new object[] {
                        employeeNo,
                        documentNo}, this.GetApproversOperationCompleted, userState);
        }
        
        private void OnGetApproversOperationCompleted(object arg) {
            if ((this.GetApproversCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApproversCompleted(this, new GetApproversCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectionComments", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectionComments_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string RejectionComments(string documentNo) {
            object[] results = this.Invoke("RejectionComments", new object[] {
                        documentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RejectionCommentsAsync(string documentNo) {
            this.RejectionCommentsAsync(documentNo, null);
        }
        
        /// <remarks/>
        public void RejectionCommentsAsync(string documentNo, object userState) {
            if ((this.RejectionCommentsOperationCompleted == null)) {
                this.RejectionCommentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectionCommentsOperationCompleted);
            }
            this.InvokeAsync("RejectionComments", new object[] {
                        documentNo}, this.RejectionCommentsOperationCompleted, userState);
        }
        
        private void OnRejectionCommentsOperationCompleted(object arg) {
            if ((this.RejectionCommentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectionCommentsCompleted(this, new RejectionCommentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveImprestReque" +
            "st", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApproveImprestRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApproveImprestRequest(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            object[] results = this.Invoke("ApproveImprestRequest", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveImprestRequestAsync(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            this.ApproveImprestRequestAsync(employeeNoa46, documentNoa46, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void ApproveImprestRequestAsync(string employeeNoa46, string documentNoa46, string approverEmpNo, object userState) {
            if ((this.ApproveImprestRequestOperationCompleted == null)) {
                this.ApproveImprestRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveImprestRequestOperationCompleted);
            }
            this.InvokeAsync("ApproveImprestRequest", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo}, this.ApproveImprestRequestOperationCompleted, userState);
        }
        
        private void OnApproveImprestRequestOperationCompleted(object arg) {
            if ((this.ApproveImprestRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveImprestRequestCompleted(this, new ApproveImprestRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectImprestReques" +
            "t", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectImprestRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool RejectImprestRequest(string employeeNoa46, string documentNoa46, string rejectionComments, string approverEmpNo) {
            object[] results = this.Invoke("RejectImprestRequest", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RejectImprestRequestAsync(string employeeNoa46, string documentNoa46, string rejectionComments, string approverEmpNo) {
            this.RejectImprestRequestAsync(employeeNoa46, documentNoa46, rejectionComments, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void RejectImprestRequestAsync(string employeeNoa46, string documentNoa46, string rejectionComments, string approverEmpNo, object userState) {
            if ((this.RejectImprestRequestOperationCompleted == null)) {
                this.RejectImprestRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectImprestRequestOperationCompleted);
            }
            this.InvokeAsync("RejectImprestRequest", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments,
                        approverEmpNo}, this.RejectImprestRequestOperationCompleted, userState);
        }
        
        private void OnRejectImprestRequestOperationCompleted(object arg) {
            if ((this.RejectImprestRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectImprestRequestCompleted(this, new RejectImprestRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveLeave", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApproveLeave_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApproveLeave(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            object[] results = this.Invoke("ApproveLeave", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveLeaveAsync(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            this.ApproveLeaveAsync(employeeNoa46, documentNoa46, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void ApproveLeaveAsync(string employeeNoa46, string documentNoa46, string approverEmpNo, object userState) {
            if ((this.ApproveLeaveOperationCompleted == null)) {
                this.ApproveLeaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveLeaveOperationCompleted);
            }
            this.InvokeAsync("ApproveLeave", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo}, this.ApproveLeaveOperationCompleted, userState);
        }
        
        private void OnApproveLeaveOperationCompleted(object arg) {
            if ((this.ApproveLeaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveLeaveCompleted(this, new ApproveLeaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectLeave", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectLeave_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool RejectLeave(string employeeNoa46, string documentNoa46, string rejectionComments, string approverEmpNo) {
            object[] results = this.Invoke("RejectLeave", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RejectLeaveAsync(string employeeNoa46, string documentNoa46, string rejectionComments, string approverEmpNo) {
            this.RejectLeaveAsync(employeeNoa46, documentNoa46, rejectionComments, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void RejectLeaveAsync(string employeeNoa46, string documentNoa46, string rejectionComments, string approverEmpNo, object userState) {
            if ((this.RejectLeaveOperationCompleted == null)) {
                this.RejectLeaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectLeaveOperationCompleted);
            }
            this.InvokeAsync("RejectLeave", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments,
                        approverEmpNo}, this.RejectLeaveOperationCompleted, userState);
        }
        
        private void OnRejectLeaveOperationCompleted(object arg) {
            if ((this.RejectLeaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectLeaveCompleted(this, new RejectLeaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveStaffRequisi" +
            "tion", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApproveStaffRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApproveStaffRequisition(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            object[] results = this.Invoke("ApproveStaffRequisition", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveStaffRequisitionAsync(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            this.ApproveStaffRequisitionAsync(employeeNoa46, documentNoa46, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void ApproveStaffRequisitionAsync(string employeeNoa46, string documentNoa46, string approverEmpNo, object userState) {
            if ((this.ApproveStaffRequisitionOperationCompleted == null)) {
                this.ApproveStaffRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveStaffRequisitionOperationCompleted);
            }
            this.InvokeAsync("ApproveStaffRequisition", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo}, this.ApproveStaffRequisitionOperationCompleted, userState);
        }
        
        private void OnApproveStaffRequisitionOperationCompleted(object arg) {
            if ((this.ApproveStaffRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveStaffRequisitionCompleted(this, new ApproveStaffRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectStaffRequisit" +
            "ion", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectStaffRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool RejectStaffRequisition(string employeeNoa46, string documentNoa46, string rejectionComments) {
            object[] results = this.Invoke("RejectStaffRequisition", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RejectStaffRequisitionAsync(string employeeNoa46, string documentNoa46, string rejectionComments) {
            this.RejectStaffRequisitionAsync(employeeNoa46, documentNoa46, rejectionComments, null);
        }
        
        /// <remarks/>
        public void RejectStaffRequisitionAsync(string employeeNoa46, string documentNoa46, string rejectionComments, object userState) {
            if ((this.RejectStaffRequisitionOperationCompleted == null)) {
                this.RejectStaffRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectStaffRequisitionOperationCompleted);
            }
            this.InvokeAsync("RejectStaffRequisition", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments}, this.RejectStaffRequisitionOperationCompleted, userState);
        }
        
        private void OnRejectStaffRequisitionOperationCompleted(object arg) {
            if ((this.RejectStaffRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectStaffRequisitionCompleted(this, new RejectStaffRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveRequisition", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApproveRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApproveRequisition(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            object[] results = this.Invoke("ApproveRequisition", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveRequisitionAsync(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            this.ApproveRequisitionAsync(employeeNoa46, documentNoa46, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void ApproveRequisitionAsync(string employeeNoa46, string documentNoa46, string approverEmpNo, object userState) {
            if ((this.ApproveRequisitionOperationCompleted == null)) {
                this.ApproveRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveRequisitionOperationCompleted);
            }
            this.InvokeAsync("ApproveRequisition", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo}, this.ApproveRequisitionOperationCompleted, userState);
        }
        
        private void OnApproveRequisitionOperationCompleted(object arg) {
            if ((this.ApproveRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveRequisitionCompleted(this, new ApproveRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveRequisitionC" +
            "opy", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApproveRequisitionCopy_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApproveRequisitionCopy(string employeeNoa46, string documentNoa46, string comments, string approverEmpNo) {
            object[] results = this.Invoke("ApproveRequisitionCopy", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        comments,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveRequisitionCopyAsync(string employeeNoa46, string documentNoa46, string comments, string approverEmpNo) {
            this.ApproveRequisitionCopyAsync(employeeNoa46, documentNoa46, comments, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void ApproveRequisitionCopyAsync(string employeeNoa46, string documentNoa46, string comments, string approverEmpNo, object userState) {
            if ((this.ApproveRequisitionCopyOperationCompleted == null)) {
                this.ApproveRequisitionCopyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveRequisitionCopyOperationCompleted);
            }
            this.InvokeAsync("ApproveRequisitionCopy", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        comments,
                        approverEmpNo}, this.ApproveRequisitionCopyOperationCompleted, userState);
        }
        
        private void OnApproveRequisitionCopyOperationCompleted(object arg) {
            if ((this.ApproveRequisitionCopyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveRequisitionCopyCompleted(this, new ApproveRequisitionCopyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectRequisition", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool RejectRequisition(string employeeNoa46, string documentNoa46, string rejectionComments) {
            object[] results = this.Invoke("RejectRequisition", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RejectRequisitionAsync(string employeeNoa46, string documentNoa46, string rejectionComments) {
            this.RejectRequisitionAsync(employeeNoa46, documentNoa46, rejectionComments, null);
        }
        
        /// <remarks/>
        public void RejectRequisitionAsync(string employeeNoa46, string documentNoa46, string rejectionComments, object userState) {
            if ((this.RejectRequisitionOperationCompleted == null)) {
                this.RejectRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectRequisitionOperationCompleted);
            }
            this.InvokeAsync("RejectRequisition", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments}, this.RejectRequisitionOperationCompleted, userState);
        }
        
        private void OnRejectRequisitionOperationCompleted(object arg) {
            if ((this.RejectRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectRequisitionCompleted(this, new RejectRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApprovePurchaseOrde" +
            "r", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApprovePurchaseOrder_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApprovePurchaseOrder(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            object[] results = this.Invoke("ApprovePurchaseOrder", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApprovePurchaseOrderAsync(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            this.ApprovePurchaseOrderAsync(employeeNoa46, documentNoa46, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void ApprovePurchaseOrderAsync(string employeeNoa46, string documentNoa46, string approverEmpNo, object userState) {
            if ((this.ApprovePurchaseOrderOperationCompleted == null)) {
                this.ApprovePurchaseOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApprovePurchaseOrderOperationCompleted);
            }
            this.InvokeAsync("ApprovePurchaseOrder", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo}, this.ApprovePurchaseOrderOperationCompleted, userState);
        }
        
        private void OnApprovePurchaseOrderOperationCompleted(object arg) {
            if ((this.ApprovePurchaseOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApprovePurchaseOrderCompleted(this, new ApprovePurchaseOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectPurchaseOrder" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectPurchaseOrder_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool RejectPurchaseOrder(string employeeNoa46, string documentNoa46, string rejectionComments) {
            object[] results = this.Invoke("RejectPurchaseOrder", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RejectPurchaseOrderAsync(string employeeNoa46, string documentNoa46, string rejectionComments) {
            this.RejectPurchaseOrderAsync(employeeNoa46, documentNoa46, rejectionComments, null);
        }
        
        /// <remarks/>
        public void RejectPurchaseOrderAsync(string employeeNoa46, string documentNoa46, string rejectionComments, object userState) {
            if ((this.RejectPurchaseOrderOperationCompleted == null)) {
                this.RejectPurchaseOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectPurchaseOrderOperationCompleted);
            }
            this.InvokeAsync("RejectPurchaseOrder", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments}, this.RejectPurchaseOrderOperationCompleted, userState);
        }
        
        private void OnRejectPurchaseOrderOperationCompleted(object arg) {
            if ((this.RejectPurchaseOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectPurchaseOrderCompleted(this, new RejectPurchaseOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveRFX", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApproveRFX_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApproveRFX(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            object[] results = this.Invoke("ApproveRFX", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveRFXAsync(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            this.ApproveRFXAsync(employeeNoa46, documentNoa46, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void ApproveRFXAsync(string employeeNoa46, string documentNoa46, string approverEmpNo, object userState) {
            if ((this.ApproveRFXOperationCompleted == null)) {
                this.ApproveRFXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveRFXOperationCompleted);
            }
            this.InvokeAsync("ApproveRFX", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo}, this.ApproveRFXOperationCompleted, userState);
        }
        
        private void OnApproveRFXOperationCompleted(object arg) {
            if ((this.ApproveRFXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveRFXCompleted(this, new ApproveRFXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectRFX", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectRFX_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool RejectRFX(string employeeNoa46, string documentNoa46, string rejectionComments) {
            object[] results = this.Invoke("RejectRFX", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RejectRFXAsync(string employeeNoa46, string documentNoa46, string rejectionComments) {
            this.RejectRFXAsync(employeeNoa46, documentNoa46, rejectionComments, null);
        }
        
        /// <remarks/>
        public void RejectRFXAsync(string employeeNoa46, string documentNoa46, string rejectionComments, object userState) {
            if ((this.RejectRFXOperationCompleted == null)) {
                this.RejectRFXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectRFXOperationCompleted);
            }
            this.InvokeAsync("RejectRFX", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments}, this.RejectRFXOperationCompleted, userState);
        }
        
        private void OnRejectRFXOperationCompleted(object arg) {
            if ((this.RejectRFXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectRFXCompleted(this, new RejectRFXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveBidAnalysis", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApproveBidAnalysis_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApproveBidAnalysis(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            object[] results = this.Invoke("ApproveBidAnalysis", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveBidAnalysisAsync(string employeeNoa46, string documentNoa46, string approverEmpNo) {
            this.ApproveBidAnalysisAsync(employeeNoa46, documentNoa46, approverEmpNo, null);
        }
        
        /// <remarks/>
        public void ApproveBidAnalysisAsync(string employeeNoa46, string documentNoa46, string approverEmpNo, object userState) {
            if ((this.ApproveBidAnalysisOperationCompleted == null)) {
                this.ApproveBidAnalysisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveBidAnalysisOperationCompleted);
            }
            this.InvokeAsync("ApproveBidAnalysis", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        approverEmpNo}, this.ApproveBidAnalysisOperationCompleted, userState);
        }
        
        private void OnApproveBidAnalysisOperationCompleted(object arg) {
            if ((this.ApproveBidAnalysisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveBidAnalysisCompleted(this, new ApproveBidAnalysisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectBidAnalysis", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectBidAnalysis_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool RejectBidAnalysis(string employeeNoa46, string documentNoa46, string rejectionComments) {
            object[] results = this.Invoke("RejectBidAnalysis", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RejectBidAnalysisAsync(string employeeNoa46, string documentNoa46, string rejectionComments) {
            this.RejectBidAnalysisAsync(employeeNoa46, documentNoa46, rejectionComments, null);
        }
        
        /// <remarks/>
        public void RejectBidAnalysisAsync(string employeeNoa46, string documentNoa46, string rejectionComments, object userState) {
            if ((this.RejectBidAnalysisOperationCompleted == null)) {
                this.RejectBidAnalysisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectBidAnalysisOperationCompleted);
            }
            this.InvokeAsync("RejectBidAnalysis", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments}, this.RejectBidAnalysisOperationCompleted, userState);
        }
        
        private void OnRejectBidAnalysisOperationCompleted(object arg) {
            if ((this.RejectBidAnalysisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectBidAnalysisCompleted(this, new RejectBidAnalysisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApprovePaymentVouch" +
            "er", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="ApprovePaymentVoucher_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ApprovePaymentVoucher(string documentNoa46, string employeeNo) {
            object[] results = this.Invoke("ApprovePaymentVoucher", new object[] {
                        documentNoa46,
                        employeeNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApprovePaymentVoucherAsync(string documentNoa46, string employeeNo) {
            this.ApprovePaymentVoucherAsync(documentNoa46, employeeNo, null);
        }
        
        /// <remarks/>
        public void ApprovePaymentVoucherAsync(string documentNoa46, string employeeNo, object userState) {
            if ((this.ApprovePaymentVoucherOperationCompleted == null)) {
                this.ApprovePaymentVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApprovePaymentVoucherOperationCompleted);
            }
            this.InvokeAsync("ApprovePaymentVoucher", new object[] {
                        documentNoa46,
                        employeeNo}, this.ApprovePaymentVoucherOperationCompleted, userState);
        }
        
        private void OnApprovePaymentVoucherOperationCompleted(object arg) {
            if ((this.ApprovePaymentVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApprovePaymentVoucherCompleted(this, new ApprovePaymentVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectPaymentVouche" +
            "r", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="RejectPaymentVoucher_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool RejectPaymentVoucher(string employeeNoa46, string documentNoa46, string rejectionComments) {
            object[] results = this.Invoke("RejectPaymentVoucher", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RejectPaymentVoucherAsync(string employeeNoa46, string documentNoa46, string rejectionComments) {
            this.RejectPaymentVoucherAsync(employeeNoa46, documentNoa46, rejectionComments, null);
        }
        
        /// <remarks/>
        public void RejectPaymentVoucherAsync(string employeeNoa46, string documentNoa46, string rejectionComments, object userState) {
            if ((this.RejectPaymentVoucherOperationCompleted == null)) {
                this.RejectPaymentVoucherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectPaymentVoucherOperationCompleted);
            }
            this.InvokeAsync("RejectPaymentVoucher", new object[] {
                        employeeNoa46,
                        documentNoa46,
                        rejectionComments}, this.RejectPaymentVoucherOperationCompleted, userState);
        }
        
        private void OnRejectPaymentVoucherOperationCompleted(object arg) {
            if ((this.RejectPaymentVoucherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectPaymentVoucherCompleted(this, new RejectPaymentVoucherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:SendApprovalRequest" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ResponseElementName="SendApprovalRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendApprovalRequest(string requestNo) {
            this.Invoke("SendApprovalRequest", new object[] {
                        requestNo});
        }
        
        /// <remarks/>
        public void SendApprovalRequestAsync(string requestNo) {
            this.SendApprovalRequestAsync(requestNo, null);
        }
        
        /// <remarks/>
        public void SendApprovalRequestAsync(string requestNo, object userState) {
            if ((this.SendApprovalRequestOperationCompleted == null)) {
                this.SendApprovalRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendApprovalRequestOperationCompleted);
            }
            this.InvokeAsync("SendApprovalRequest", new object[] {
                        requestNo}, this.SendApprovalRequestOperationCompleted, userState);
        }
        
        private void OnSendApprovalRequestOperationCompleted(object arg) {
            if ((this.SendApprovalRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendApprovalRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetOpenApprovalEntriesCompletedEventHandler(object sender, GetOpenApprovalEntriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOpenApprovalEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOpenApprovalEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetApprovedApprovalEntriesCompletedEventHandler(object sender, GetApprovedApprovalEntriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApprovedApprovalEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApprovedApprovalEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRejectedApprovalEntriesCompletedEventHandler(object sender, GetRejectedApprovalEntriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRejectedApprovalEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRejectedApprovalEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetApproversCompletedEventHandler(object sender, GetApproversCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApproversCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApproversCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectionCommentsCompletedEventHandler(object sender, RejectionCommentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectionCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectionCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApproveImprestRequestCompletedEventHandler(object sender, ApproveImprestRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveImprestRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveImprestRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectImprestRequestCompletedEventHandler(object sender, RejectImprestRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectImprestRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectImprestRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApproveLeaveCompletedEventHandler(object sender, ApproveLeaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveLeaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveLeaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectLeaveCompletedEventHandler(object sender, RejectLeaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectLeaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectLeaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApproveStaffRequisitionCompletedEventHandler(object sender, ApproveStaffRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveStaffRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveStaffRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectStaffRequisitionCompletedEventHandler(object sender, RejectStaffRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectStaffRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectStaffRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApproveRequisitionCompletedEventHandler(object sender, ApproveRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApproveRequisitionCopyCompletedEventHandler(object sender, ApproveRequisitionCopyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveRequisitionCopyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveRequisitionCopyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectRequisitionCompletedEventHandler(object sender, RejectRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApprovePurchaseOrderCompletedEventHandler(object sender, ApprovePurchaseOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApprovePurchaseOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApprovePurchaseOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectPurchaseOrderCompletedEventHandler(object sender, RejectPurchaseOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectPurchaseOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectPurchaseOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApproveRFXCompletedEventHandler(object sender, ApproveRFXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveRFXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveRFXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectRFXCompletedEventHandler(object sender, RejectRFXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectRFXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectRFXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApproveBidAnalysisCompletedEventHandler(object sender, ApproveBidAnalysisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveBidAnalysisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveBidAnalysisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectBidAnalysisCompletedEventHandler(object sender, RejectBidAnalysisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectBidAnalysisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectBidAnalysisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApprovePaymentVoucherCompletedEventHandler(object sender, ApprovePaymentVoucherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApprovePaymentVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApprovePaymentVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectPaymentVoucherCompletedEventHandler(object sender, RejectPaymentVoucherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectPaymentVoucherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectPaymentVoucherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SendApprovalRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591